const TYPOGRAPHY = {
  '.HEADER-H1': {
    fontSize: '30px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '40px',
    letterSpacing: '0.075px',
  },
  '.HEADER-H2': {
    fontSize: '24px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '32px',
    letterSpacing: '0.15px',
  },
  '.HEADER-H3': {
    fontSize: '24px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 500,
    lineHeight: '32px',
    letterSpacing: '0.15px',
  },
  '.HEADER-H4': {
    fontSize: '20px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 500,
    lineHeight: '26px',
    letterSpacing: '0.03px',
  },
  '.HEADER-H5': {
    fontSize: '20px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '26px',
    letterSpacing: '0.15px',
  },
  '.HEADER-H6': {
    fontSize: '18px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '24px',
    letterSpacing: '0.027px',
  },
  '.HEADER-H7': {
    fontSize: '14px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '20px',
    letterSpacing: '0.035px',
  },
  '.SUBTITLE-T1': {
    fontSize: '16px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 700,
    lineHeight: '20px',
    letterSpacing: '0.04px',
  },
  '.SUBTITLE-T2': {
    fontSize: '16px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '20px',
    letterSpacing: '0.04px',
  },
  '.SUBTITLE-T3': {
    fontSize: '14px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 500,
    lineHeight: '18px',
    letterSpacing: '0.15px',
  },
  '.SUBTITLE-T4': {
    fontSize: '13px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 400,
    lineHeight: '20px',
    letterSpacing: '0.15px',
  },
  '.SUBTITLE-T5': {
    fontSize: '13px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 500,
    lineHeight: '20px',
    letterSpacing: '0.15px',
  },
  '.SUBTITLE-T6': {
    fontSize: '13px',
    fontWeight: 400,
    fontFamily: 'Pretendard, sans-serif',
    lineHeight: '20px',
    letterSpacing: '0.15px',
  },
  '.SUBTITLE-T7': {
    fontSize: '12px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '16px',
    letterSpacing: '0.018px',
  },
  '.SUBTITLE-T8': {
    fontSize: '12px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: '0.15px',
  },
  '.INPUT-LABEL1': {
    fontSize: '16px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '20px',
    letterSpacing: '0.04px',
  },
  '.INPUT-LABEL2': {
    fontSize: '16px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 500,
    lineHeight: '20px',
    letterSpacing: '0.04px',
  },
  '.INPUT-FIELD': {
    fontSize: '16px',
    fontFamily: 'Pretendard, sans-serif',
    lineHeight: '20px',
    fontWeight: 400,
    letterSpacing: '0.04px',
  },
  '.INPUT-FIELD2': {
    fontSize: '14px',
    fontFamily: 'Pretendard, sans-serif',
    lineHeight: '20px',
    fontWeight: 400,
    letterSpacing: '0.035px',
  },
  '.BUTTON-LARGE': {
    fontSize: '18px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '22px',
    letterSpacing: '0.4px',
  },
  '.BUTTON-MEDIUM': {
    fontSize: '14px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '20px',
    letterSpacing: '0.4px',
  },
  '.BUTTON-SMALL': {
    fontSize: '12px',
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    lineHeight: '22px',
    letterSpacing: '0.46px',
  },

  '.GNB_ACTIVE': {
    fontFamily: 'Pretendard, sans-serif',
    fontSize: '11px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '14px',
    letterSpacing: '0.46px',
  },

  '.GNB_INACTIVE': {
    fontFamily: 'Pretendard, sans-serif',
    fontSize: '11px',
    fontStyle: 'normal',
    fontWeight: 600,
    lineHeight: '14px',
    letterSpacing: '0.46px',
  },
}

export default TYPOGRAPHY
